/**
 * Stage 5: Technical Row Classifier
 * 
 * Classifies every raw row in an inventory sheet into one of:
 *   inventory_item | ignored_header_row | ignored_empty_row |
 *   ignored_total_row | ignored_subtotal_row | ignored_signature_row |
 *   ignored_metadata_row | ignored_summary_sheet_row
 * 
 * Classification is additive labeling — no rows are deleted.
 */

import { ClassifiedRow, RowClassification, SheetStructure, COLUMN_ALIASES } from "./types";

// ─── Keyword Lists ──────────────────────────────────────────────────────────

const TOTAL_KEYWORDS = ["total", "grand total", "subtotal", "sub-total"];
const SUBTOTAL_PREFIXES = ["sum of", "count of", "average"];

const SIGNATURE_KEYWORDS = [
  "prepared by", "approved by", "checked by", "reviewed by",
  "signature", "sign:",
];

const METADATA_KEYWORDS = [
  "note:", "notes:", "disclaimer:", "date:", "page ",
  "printed on", "generated by", "report date",
];

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Build a raw data object from a row using the header cells */
const buildRawRowData = (rowData: unknown[], headerCells: unknown[]): Record<string, unknown> => {
  const raw: Record<string, unknown> = {};
  const len = Math.max(headerCells.length, rowData.length);
  for (let j = 0; j < len; j++) {
    const key = headerCells[j]?.toString() || `Column_${j + 1}`;
    raw[key] = rowData[j] ?? "";
  }
  return raw;
};

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Classifies every row in a single sheet.
 * 
 * For non-inventory sheets (summary/unknown), all rows are classified
 * as `ignored_summary_sheet_row`.
 * 
 * For inventory sheets, each row is checked against the decision tree.
 */
export const classifyRows = (
  sheet: SheetStructure,
  sourceFileName: string
): ClassifiedRow[] => {
  const results: ClassifiedRow[] = [];
  const { rawRows, headerCells, headerRowIndex, sheetName, sheetType, columnMap } = sheet;

  // Non-inventory sheets: all rows are summary sheet rows
  if (sheetType !== "inventory_sheet") {
    for (let r = 0; r < rawRows.length; r++) {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData: buildRawRowData(rawRows[r], headerCells),
        classification: "ignored_summary_sheet_row",
        reason: "Non-inventory summary sheet row",
      });
    }
    return results;
  }

  // Build an index-to-field map from the column map for quick lookup
  const indexToField: Record<number, string> = {};
  for (const col of columnMap) {
    if (col.mappingType === "standard" && col.mappedField) {
      indexToField[col.columnIndex] = col.mappedField;
    }
  }

  for (let r = 0; r < rawRows.length; r++) {
    const rowData = rawRows[r];
    const rawRowData = buildRawRowData(rowData, headerCells);

    // 1. Pre-header or header row
    if (r <= headerRowIndex) {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData,
        classification: "ignored_header_row",
        reason: r === headerRowIndex ? "Header row" : "Pre-header metadata row",
      });
      continue;
    }

    // 2. Completely empty row
    const isEmpty = rowData.every(
      (cell: any) => cell === null || cell === undefined || String(cell).trim() === ""
    );
    if (isEmpty) {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData,
        classification: "ignored_empty_row",
        reason: "Fully empty row",
      });
      continue;
    }

    // Extract item and description values for classification checks
    const itemIdx = Object.entries(indexToField).find(([, f]) => f === "item");
    const descIdx = Object.entries(indexToField).find(([, f]) => f === "description");
    const itemVal = itemIdx ? String(rowData[Number(itemIdx[0])] ?? "").trim() : "";
    const descVal = descIdx ? String(rowData[Number(descIdx[0])] ?? "").trim() : "";

    // 3. Repeated header row (item column contains a known alias)
    const itemNormalized = itemVal.toLowerCase().replace(/[^a-z0-9]/g, "");
    const isRepeatedHeader = COLUMN_ALIASES.item.includes(itemNormalized) ||
      itemNormalized === "item" || itemNormalized === "itemcode" || itemNormalized === "materialcode";
    if (isRepeatedHeader) {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData,
        classification: "ignored_header_row",
        reason: "Repeated header row",
      });
      continue;
    }

    // 4. Both item AND description empty
    if (itemVal === "" && descVal === "") {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData,
        classification: "ignored_empty_row",
        reason: "Empty row (no item code and no description)",
      });
      continue;
    }

    // 5. Total/subtotal row (check first 5 columns)
    let isTotalRow = false;
    let isSubtotalRow = false;
    for (let ci = 0; ci < Math.min(5, rowData.length); ci++) {
      const cell = rowData[ci];
      if (cell === null || cell === undefined) continue;
      const cellStr = String(cell).toLowerCase().trim();
      if (TOTAL_KEYWORDS.includes(cellStr)) { isTotalRow = true; break; }
      if (SUBTOTAL_PREFIXES.some(p => cellStr.startsWith(p))) { isSubtotalRow = true; break; }
    }

    if (isTotalRow) {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData,
        classification: "ignored_total_row",
        reason: "Total/subtotal aggregation row",
      });
      continue;
    }

    if (isSubtotalRow) {
      results.push({
        sourceFileName,
        sheetName,
        originalRowNumber: r + 1,
        rawRowData,
        classification: "ignored_subtotal_row",
        reason: "Subtotal/aggregation formula row",
      });
      continue;
    }

    // 6. Signature row (≤4 non-blank cells with signature keywords)
    const nonBlankCells = rowData.filter(
      (cell: any) => cell !== null && cell !== undefined && String(cell).trim() !== ""
    );

    if (nonBlankCells.length <= 4) {
      const matchedSig = nonBlankCells.find((cell: any) => {
        const cellStr = String(cell).toLowerCase().trim();
        return SIGNATURE_KEYWORDS.some(kw => cellStr.includes(kw));
      });

      if (matchedSig) {
        results.push({
          sourceFileName,
          sheetName,
          originalRowNumber: r + 1,
          rawRowData,
          classification: "ignored_signature_row",
          reason: `Signature/signatory row (${String(matchedSig).trim()})`,
        });
        continue;
      }

      // 7. Metadata/footer row
      const matchedMeta = nonBlankCells.find((cell: any) => {
        const cellStr = String(cell).toLowerCase().trim();
        return METADATA_KEYWORDS.some(kw => cellStr.startsWith(kw) || cellStr.includes(kw));
      });

      if (matchedMeta) {
        results.push({
          sourceFileName,
          sheetName,
          originalRowNumber: r + 1,
          rawRowData,
          classification: "ignored_metadata_row",
          reason: `Technical metadata row (${String(matchedMeta).trim()})`,
        });
        continue;
      }
    }

    // 8. Default: inventory_item — pass to extraction
    results.push({
      sourceFileName,
      sheetName,
      originalRowNumber: r + 1,
      rawRowData,
      classification: "inventory_item",
      reason: "Candidate inventory item row",
    });
  }

  return results;
};
